Repository SKNETWORKS-FAMILY-AICAMP/SKN09-4th-1Team, pull requests merged in 2025-04, with the labels that each got.

#16 11 feat 의뢰인 정보 입력 처리 뷰 구현
  .gitignore
  lawquick/.gitignore
  lawquick/chat/__pycache__/apps.cpython-312.pyc
  lawquick/chat/__pycache__/models.cpython-312.pyc
  lawquick/chat/apps.py
  lawquick/db.sqlite3
  lawquick/lawquick/__pycache__/settings.cpython-312.pyc
  lawquick/lawquick/__pycache__/urls.cpython-312.pyc
  lawquick/lawquick/settings.py
  lawquick/lawquick/urls.py
  lawquick/static/css/common.css
  lawquick/static/css/lawquick-info.css
  lawquick/static/css/lawquick-login.css
  lawquick/static/css/lawquick-search.css
  lawquick/static/images/arrow-down.svg
  lawquick/static/js/info.js
  lawquick/templates/common/header.html
  lawquick/templates/user/home_01.html
  lawquick/templates/user/info.html
  lawquick/templates/user/search_01.html
  lawquick/templates/user/search_02.html
  lawquick/templates/user/search_03.html
  lawquick/user/__pycache__/models.cpython-312.pyc
  lawquick/user/migrations/0001_initial.py
  lawquick/user/migrations/0002_alter_userinfo_marriage_duration.py
  lawquick/user/models.py
  lawquick/user/urls.py
  lawquick/user/views.py
Labels: feature

#19 9 feat 의뢰인 정보 입력 기능 구현
  .gitignore
  lawquick/chat/__pycache__/apps.cpython-312.pyc
  lawquick/chat/__pycache__/models.cpython-312.pyc
  lawquick/lawquick/__pycache__/settings.cpython-312.pyc
  lawquick/lawquick/__pycache__/urls.cpython-312.pyc
  lawquick/lawquick/settings.py
  lawquick/static/css/lawquick-info.css
  lawquick/static/js/info.js
  lawquick/templates/user/info.html
  lawquick/user/__pycache__/models.cpython-312.pyc
  lawquick/user/forms.py
  lawquick/user/migrations/0001_initial.py
  lawquick/user/models.py
  lawquick/user/tests.py
  lawquick/user/urls.py
  lawquick/user/views.py
Labels: feature

#20 FEAT: 로그인 및 비밀번호 찾기 기능 구현
  .gitignore
  lawquick/.gitignore
  lawquick/chat/__pycache__/__init__.cpython-312.pyc
  lawquick/chat/__pycache__/admin.cpython-312.pyc
  lawquick/chat/__pycache__/apps.cpython-312.pyc
  lawquick/chat/__pycache__/models.cpython-312.pyc
  lawquick/chat/migrations/__pycache__/__init__.cpython-312.pyc
  lawquick/lawquick/__pycache__/__init__.cpython-312.pyc
  lawquick/lawquick/__pycache__/settings.cpython-312.pyc
  lawquick/lawquick/__pycache__/urls.cpython-312.pyc
  lawquick/static/css/common.css
  lawquick/static/css/lawquick-login.css
  lawquick/static/css/lawquick-search.css
  lawquick/templates/user/home_01.html
  lawquick/templates/user/search_01.html
  lawquick/templates/user/search_02.html
  lawquick/templates/user/search_03.html
  lawquick/user/__pycache__/__init__.cpython-312.pyc
  lawquick/user/__pycache__/admin.cpython-312.pyc
  lawquick/user/__pycache__/apps.cpython-312.pyc
  lawquick/user/__pycache__/models.cpython-312.pyc
  lawquick/user/migrations/__pycache__/__init__.cpython-312.pyc
  lawquick/user/repositories/user_repository.py
  lawquick/user/services/auth_service.py
  lawquick/user/urls.py
  lawquick/user/views.py
Labels: feature, done

#23 Fix: 회원가입 기능 전체 구현 (#2)
  lawquick/lawquick/settings.py
  lawquick/static/css/lawquick-join.css
  lawquick/templates/email_verification.html
  lawquick/templates/user/home_01.html
  lawquick/templates/user/join_01.html
  lawquick/templates/user/join_02.html
  lawquick/templates/user/join_03.html
  lawquick/templates/user/join_04.html
  lawquick/templates/user/join_p_terms_privacy.html
  lawquick/templates/user/join_p_terms_service.html
  lawquick/user/admin.py
  lawquick/user/models.py
  lawquick/user/urls.py
  lawquick/user/views.py
Labels: feature

#24 22 feat 비회원 채팅 메인 페이지 db 연동
  lawquick/chat/admin.py
  lawquick/chat/urls.py
  lawquick/chat/views.py
  lawquick/templates/chat/chat_guest_00.html
  lawquick/templates/chat/chat_guest_01.html
  lawquick/templates/user/home_01.html
Labels: feature

#26 Chat
  lawquick/chat/admin.py
  lawquick/chat/migrations/__pycache__/__init__.cpython-312.pyc
  lawquick/chat/urls.py
  lawquick/chat/views.py
  lawquick/lawquick/settings.py
  lawquick/lawquick/urls.py
  lawquick/static/css/chat_common.css
  lawquick/static/css/chat_member_common copy.css
  lawquick/static/css/chat_member_common.css
  lawquick/static/css/common.css
  lawquick/static/css/lawquick-chat-guest.css
  lawquick/static/css/lawquick-chat-member.css
  lawquick/static/css/lawquick-chat.css
  lawquick/static/js/chat_member_sidebar.js
  lawquick/templates/chat/chat_guest_00.html
  lawquick/templates/chat/chat_guest_01.html
  lawquick/templates/chat/chat_member_00.html
  lawquick/templates/chat/chat_member_01.html
  lawquick/templates/chat/sidebar.html
  lawquick/templates/common/chat_header.html
  lawquick/templates/common/chat_member-header.html
  lawquick/templates/user/home_01.html
  lawquick/user/migrations/__pycache__/__init__.cpython-312.pyc
  lawquick/user/views.py
Labels: feature

#27 Chat
  lawquick/chat/admin.py
  lawquick/chat/migrations/__pycache__/__init__.cpython-312.pyc
  lawquick/chat/urls.py
  lawquick/chat/views.py
  lawquick/lawquick/settings.py
  lawquick/lawquick/urls.py
  lawquick/static/css/chat_common.css
  lawquick/static/css/chat_member_common copy.css
  lawquick/static/css/chat_member_common.css
  lawquick/static/css/common.css
  lawquick/static/css/lawquick-chat-guest.css
  lawquick/static/css/lawquick-chat-member.css
  lawquick/static/css/lawquick-chat.css
  lawquick/static/js/chat_member_sidebar.js
  lawquick/templates/chat/chat_guest_00.html
  lawquick/templates/chat/chat_guest_01.html
  lawquick/templates/chat/chat_member_00.html
  lawquick/templates/chat/chat_member_01.html
  lawquick/templates/chat/sidebar.html
  lawquick/templates/common/chat_header.html
  lawquick/templates/common/chat_member-header.html
  lawquick/templates/user/home_01.html
  lawquick/user/migrations/__pycache__/__init__.cpython-312.pyc
  lawquick/user/views.py
Labels: feature

#32 29 yml and docker file
  docker-compose.yml
  lawquick/Dockerfile
  lawquick/lawquick/settings.py
Labels: docs

#36 33 read me 작성
  README.md
  lawquick/Dockerfile
Labels: docs

#38 TEST: Pytest code
  lawquick/.pytest.ini
  lawquick/chat/tests/chat_entry.py
  lawquick/chat/tests/chat_main.py
  lawquick/lawquick/urls.py
  lawquick/templates/user/join_03.html
  lawquick/user/tests/__init__.py
  lawquick/user/tests/test_auth.py
  lawquick/user/tests/test_info_submit.py
  lawquick/user/tests/test_password_search.py
  lawquick/user/tests/test_signup.py
  lawquick/user/tests/test_static_pages.py
Labels: done
